### PR TITLE
Fix Combo Boxes

### PR DESCRIPTION
**Pull request by micsthepick**
simple .cb changes to make combo boxes work properly when using a gui, NOTE: doesn't fix some issues with using cb.exe -D=USE_WCOMBOBOX

### CODE REVIEW

**Comment by micsthepick** [comment]
I've done some testing, and it seems that this fix leads to crashes, not sure why yet

**Comment by VisualCodeBase** [comment]
thank you.
i know that about the -D switch
the primary intention was to use wComboBox
but because of crash problem when adding and deleting plugs that use it
i disabled it and wrote a temporary code to use windows combo

**Comment by micsthepick** [comment]
whenever I select a combo box in this branch, it crashes (without using -D=USE_WCOMBOBOX)

**Comment by VisualCodeBase** [comment]
fixed

**Pull request closed without merging**
